### ISSUE TITLE
Pika is blocking

### ISSUE THREAD

**Issue by euhruska** [radical-collaboration/extasy-grlsd#110]
Pika is blocking? This happened after bluewaters was restarted.
```
2019-01-10 13:09:51,940: radical.entk.appmanager.0000: MainProcess                     : MainThread     : ERROR   : Error in AppManager: [Errno -3] Temporary failure in name
resolution
Traceback (most recent call last):
  File "/scratch1/eh22/conda/envs/extasy16/lib/python2.7/site-packages/radical/entk/appman/appmanager.py", line 279, in run
    setup = self._setup_mqs()
  File "/scratch1/eh22/conda/envs/extasy16/lib/python2.7/site-packages/radical/entk/appman/appmanager.py", line 547, in _setup_mqs
    mq_connection = pika.BlockingConnection(pika.ConnectionParameters(host=self._mq_hostname, port=self._port))
  File "/scratch1/eh22/conda/envs/extasy16/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 377, in __init__
    self._process_io_for_connection_setup()
  File "/scratch1/eh22/conda/envs/extasy16/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 417, in _process_io_for_connection_setup
    self._open_error_result.is_ready)
  File "/scratch1/eh22/conda/envs/extasy16/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 469, in _flush_output
    raise maybe_exception
gaierror: [Errno -3] Temporary failure in name resolution
```

**Comment by euhruska** [comment]
happens only with ```two.radical-project.org``` rabbit-mq server, not with local rabbit-mq server

**Comment by vivek-bala** [comment]
Hey Eugen, can you tell me the port number of the rmq server you are using? I can check its status for you.

**Comment by euhruska** [comment]
port 33134

**Comment by vivek-bala** [comment]
Hey Eugen, I have restarted the rabbitmq server. You can try it again now. Let me know how it goes.

**Comment by euhruska** [comment]
works
