### ISSUE TITLE
input/output error

### ISSUE THREAD

**Issue by euhruska** [radical-collaboration/extasy-grlsd#112]
got this input/output error, I saw a recommendation to restart for a similar error?

```
python extasy_tica3.py --Kconfig settings_extasy_tica3_villin_long_noko.wcfg 2>&1
| tee log_extasy_tica3_villin_long_noko.log
leonardo.rice.edu
using gpus
{'queue': 'normal', 'resource': 'ncsa.bw_aprun', 'cpus': 800, 'project': 'bamm', 'access_schema': 'gsissh', 'gpus': 50, 'walltime': 2880}
shared_data_all ['settings_extasy_tica3_villin_long_noko.wcfg', './files-villin//system-5.xml', './files-villin//integrator-5.xml', './files-villin/villin-folded-ca.pdb', './inp_files/run-openmm-xml3.py', './files-villin/villin.pdb', './helper_scripts/run-tica-msm5.py', './helper_scripts/analyze3.py']
Error: [Errno 5] Input/output error
Traceback (most recent call last):
  File "extasy_tica3.py", line 309, in <module>
    appman = AppManager(hostname='two.radical-project.org', port=33134)#port=args.port)
  File "/scratch1/eh22/conda/envs/extasy16/lib/python2.7/site-packages/radical/entk/appman/appmanager.py", line 72, in __init__
    self._uid = ru.generate_id('appmanager.%(item_counter)04d', ru.ID_CUSTOM, namespace=self._sid)
  File "/scratch1/eh22/conda/envs/extasy16/lib/python2.7/site-packages/radical/utils/ids.py", line 179,
in generate_id
    return _generate_id(template, prefix, namespace)
  File "/scratch1/eh22/conda/envs/extasy16/lib/python2.7/site-packages/radical/utils/ids.py", line 248,
in _generate_id
    os.close(fd)
OSError: [Errno 5] Input/output error
```

**Comment by andre-merzky** [comment]
Hi Eugen - is `$HOME/.radical/` accessible?  Or the file system full?  The above indicates an error when trying to create a very small file which keeps state across runs (session IDs etc).

**Comment by euhruska** [comment]
~/.radical is accessible and I can create new files, but I get some temporary swap error

**Comment by euhruska** [comment]
apparently restarting the client fixed this issue
