### ISSUE TITLE
wfprocessor error

### ISSUE THREAD

**Issue by euhruska** [radical-collaboration/extasy-grlsd#25]
I saw this error, it didn't fail the openmm unit or other units. Can we safely ignore this?
```
2018-01-14 12:14:26,050: radical.entk.wfprocessor: wfprocessor                     : enqueue-thread : ERROR   : Error while updating stage state, rolling back. Error: 
2018-01-14 12:14:26,050: radical.entk.wfprocessor: wfprocessor                     : enqueue-thread : ERROR   : Transition of radical.entk.stage.0002 to DESCRIBED state failed, error: 
2018-01-14 12:14:26,051: radical.entk.wfprocessor: wfprocessor                     : enqueue-thread : ERROR   : Error in enqueue-thread: 
Traceback (most recent call last):
  File "/Users/eh/anaconda4/envs/extasy4/lib/python2.7/site-packages/radical/entk/appman/wfprocessor.py", line 325, in _enqueue
    logger=self._logger)
  File "/Users/eh/anaconda4/envs/extasy4/lib/python2.7/site-packages/radical/entk/utils/init_transition.py", line 40, in transition
    local_prof = profiler)
  File "/Users/eh/anaconda4/envs/extasy4/lib/python2.7/site-packages/radical/entk/utils/sync_initiator.py", line 25, in sync_with_master
    correlation_id = corr_id
  File "/Users/eh/anaconda4/envs/extasy4/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 2077, in basic_publish
    mandatory, immediate)
  File "/Users/eh/anaconda4/envs/extasy4/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 2163, in publish
    immediate=immediate)
  File "/Users/eh/anaconda4/envs/extasy4/lib/python2.7/site-packages/pika/channel.py", line 415, in basic_publish
    raise exceptions.ChannelClosed()
ChannelClosed

Exception in thread enqueue-thread:
Traceback (most recent call last):
  File "/Users/eh/anaconda4/envs/extasy4/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/Users/eh/anaconda4/envs/extasy4/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Users/eh/anaconda4/envs/extasy4/lib/python2.7/site-packages/radical/entk/appman/wfprocessor.py", line 348, in _enqueue
    raise Error(text=ex)
Error: Error: 
```

**Comment by vivek-bala** [comment]
Yes, I believe this should terminate any current runs. Is that the same for you? If yes, you can ignore this.

**Comment by euhruska** [comment]
no, it doesn't terminate anything, but I guess we can ignore it
