### ISSUE TITLE
doesn't copy output files from remote to local

### ISSUE THREAD

**Issue by euhruska** [radical-collaboration/extasy-grlsd#3]
doesn't copy output files from remote to local
The directory output has  iter* subdirectories, but they are empty

Possible related to https://github.com/radical-collaboration/extasy-grlsd/issues/1

**Comment by euhruska** [comment]
reinstalled in python2.7, got now output in iter* subdirectories
(https://github.com/radical-collaboration/extasy-grlsd/issues/1 still persists)

**Comment by euhruska** [comment]
still, has to be explained why this happens

**Comment by vivek-bala** [comment]
Please try again and see if this persists with the latest devel.

**Comment by vivek-bala** [comment]
There are two kinds of staging that are possible: (i) staging between local and remote machine (scp, sftp, etc.) and (ii) staging between various locations on the remote machine (cp, mv, ln). RADICAL Pilot had a bug where you could not have both (i) and (ii) in the same script. This has been resolved in the latest devel and you should not face the error.

Does that help explain? I am not particularly sure about the source of the bug but I or you can dig out the particular commit that addresses that.

**Comment by euhruska** [comment]
this bug persists with the latest devel

**Comment by euhruska** [comment]
also the lsdmap.log isn't downloaded

**Comment by vivek-bala** [comment]
what's the value of nsave in your config file? Could you also print the output of ```radical-stack```? Thanks.

**Comment by euhruska** [comment]
radical-stack
```
  python               : 2.7.14
  pythonpath           : 
  virtualenv           : extasy

  radical.analytics    : v0.45.2-101-g8358b08@devel
  radical.pilot        : 0.47.1
  radical.utils        : 0.47
  saga                 : 0.47
```
nsave=1

**Comment by euhruska** [comment]
odd, with nsave=2 both lsdmap.log and out.gro, weight.w are saved
that's a partial solution, but it should be able to save every iteration, I don't see a reason why not

**Comment by vivek-bala** [comment]
Hmmm that is indeed odd. Did you make any changes to extasy_grlsd.py? If so, push it to the repo please.

**Comment by euhruska** [comment]
I don't have permissions, I did a pull request. Besides that no.

**Comment by vivek-bala** [comment]
I gave you write permissions as well.

**Comment by euhruska** [comment]
now it doesn't work even with nsave=2

**Comment by euhruska** [comment]
this doesn't only happend between local and remote, but also within remote, for example this doesn't work:
```
ana_task.copy_output_data += ['plot-scatter-cluster-10d.png > resource://iter_%s/plot-scatter-cluster-10d.png' % cur_iter]
```

**Comment by euhruska** [comment]
@vivek-bala suggested 
1) try examples to test download:
fails with:
```
2018-01-14 13:02:52,221: radical.entk.resource_manager: MainProcess                     : MainThread     : ERROR   : Resource request submission failed
2018-01-14 13:02:52,221: radical.entk.appmanager: MainProcess                     : MainThread     : ERROR   : Error in AppManager
Traceback (most recent call last):
  File "/Users/eh/anaconda4/envs/extasy4/lib/python2.7/site-packages/radical/entk/appman/appmanager.py", line 242, in run
    self._resource_manager._submit_resource_request()
  File "/Users/eh/anaconda4/envs/extasy4/lib/python2.7/site-packages/radical/entk/execman/resource_manager.py", line 298, in _submit_resource_request
    self._session = rp.Session(dburl=self._mlab_url)
  File "/Users/eh/anaconda4/envs/extasy4/lib/python2.7/site-packages/radical/pilot/session.py", line 216, in __init__
    raise ValueError("incomplete DBURL '%s' no db name!" % self._dburl)
ValueError: incomplete DBURL 'mongo db url' no db name!
```
2) checking umgr.0000.staging.output.0.child.log for errors:
 I saw no errors beside timeouts ```“Could not detect shell prompt (timeout)“), ```. Sometimes some files are downloaded and umgr.0000.staging.output.0.child.log shows that without any errors.

**Comment by euhruska** [comment]
1. using virtualenv instead of conda doesn't solve the failure to download, but it recognizes self._dburl and gives instead another error:
```
2018-01-14 13:35:41,423: radical.entk.resource_manager: MainProcess                     : MainThread     : ERROR   : Resource request submission failed
2018-01-14 13:35:41,424: radical.entk.appmanager: MainProcess                     : MainThread     : ERROR   : Error in AppManager
Traceback (most recent call last):
  File "/Users/eh/ve2/lib/python2.7/site-packages/radical/entk/appman/appmanager.py", line 242, in run
    self._resource_manager._submit_resource_request()
  File "/Users/eh/ve2/lib/python2.7/site-packages/radical/entk/execman/resource_manager.py", line 341, in _submit_resource_request
    self._pilot.wait([rp.ACTIVE, rp.FAILED])
AttributeError: 'module' object has no attribute 'ACTIVE'
```
This is for radical.entk/examples/simple_examples/poe.py.

**Comment by vivek-bala** [comment]
Hey Eugen,

1) Can you try this RP example: https://github.com/radical-cybertools/radical.pilot/blob/devel/examples/06_unit_output_data.py please? This will let us isolate which layer of the stack the issue is coming from.

2) 

```
2018-01-14 13:02:52,221: radical.entk.resource_manager: MainProcess                     : MainThread     : ERROR   : Resource request submission failed
2018-01-14 13:02:52,221: radical.entk.appmanager: MainProcess                     : MainThread     : ERROR   : Error in AppManager
Traceback (most recent call last):
  File "/Users/eh/anaconda4/envs/extasy4/lib/python2.7/site-packages/radical/entk/appman/appmanager.py", line 242, in run
    self._resource_manager._submit_resource_request()
  File "/Users/eh/anaconda4/envs/extasy4/lib/python2.7/site-packages/radical/entk/execman/resource_manager.py", line 298, in _submit_resource_request
    self._session = rp.Session(dburl=self._mlab_url)
  File "/Users/eh/anaconda4/envs/extasy4/lib/python2.7/site-packages/radical/pilot/session.py", line 216, in __init__
    raise ValueError("incomplete DBURL '%s' no db name!" % self._dburl)
ValueError: incomplete DBURL 'mongo db url' no db name!
```

This is probably showing up is the RADICAL_PILOT_DBURL environment variable is not set a correct
mongodb url. Can you check that please?

3) 
```
2018-01-14 13:35:41,423: radical.entk.resource_manager: MainProcess                     : MainThread     : ERROR   : Resource request submission failed
2018-01-14 13:35:41,424: radical.entk.appmanager: MainProcess                     : MainThread     : ERROR   : Error in AppManager
Traceback (most recent call last):
  File "/Users/eh/ve2/lib/python2.7/site-packages/radical/entk/appman/appmanager.py", line 242, in run
    self._resource_manager._submit_resource_request()
  File "/Users/eh/ve2/lib/python2.7/site-packages/radical/entk/execman/resource_manager.py", line 341, in _submit_resource_request
    self._pilot.wait([rp.ACTIVE, rp.FAILED])
AttributeError: 'module' object has no attribute 'ACTIVE'
```

This is because of a change in the state names in RP. We need to enable the legacy state names. You can do so by ```export RP_ENABLE_OLD_DEFINES=True```

My guess is that you came across 2 and 3 because you opened a new session(?), I will advise setting all the environment variables documented in the [README](https://github.com/radical-collaboration/extasy-grlsd) into your bashrc. 

Also feel free to attach all your logs from the local machine as well as from Blue Waters here in the ticket.

**Comment by euhruska** [comment]
1. The 06_unit_output_data.py get's stuck with for me at gathering results, here the logs:
[rp.session.EugenHruska.local.eh.017547.0001.zip](https://github.com/radical-collaboration/extasy-grlsd/files/1637119/rp.session.EugenHruska.local.eh.017547.0001.zip)

**Comment by andre-merzky** [comment]
Looks like the pilot failed, and RP attempts to terminate, which does not succeed, things hang...  Can you please also attach the pilot sandbox?  Thanks!

**Comment by euhruska** [comment]
collecting all the outputfile on bluewaters works, removing important label

**Comment by vivek-bala** [comment]
Good that you have a solution. But do provide the pilot sandbox (with its units and logs) though. The download attribute should automatically bring the files to your local machine. I think that would save a lot of human effort in moving the files.

**Comment by euhruska** [comment]
the issue was that out of the files to download one was missing, so no other file was downloaded.
Works now, closing
