### ISSUE TITLE
shutdown long

### ISSUE THREAD

**Issue by euhruska** [radical-collaboration/extasy-grlsd#38]
shutdown takes too long, too many Ctrl+C and too many error messages to be comfortable:
```
^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[^C2018-01-26 00:41:06,982: radical.entk.wfprocessor: wfprocessor                     : MainThread     : ERROR   : Execution interrupted by user (you probably hit Ctrl+C), trying to cancel wfprocessor process gracefully...
2018-01-26 00:41:06,982: radical.entk.wfprocessor: wfprocessor                     : MainThread     : INFO    : Terminating enqueue-thread
2018-01-26 00:41:06,985: radical.entk.wfprocessor: wfprocessor                     : enqueue-thread : INFO    : Enqueue thread terminated
2018-01-26 00:41:06,986: radical.entk.task_manager: task-manager                    : MainThread     : ERROR   : Execution interrupted by user (you probably hit Ctrl+C), trying to cancel tmgr process gracefully...
2018-01-26 00:41:06,988: radical.entk.wfprocessor: wfprocessor                     : enqueue-thread : ERROR   : Error in enqueue-thread: 
Traceback (most recent call last):
  File "/scratch1/eh22/conda/envs/extasy2/lib/python2.7/site-packages/radical/entk/appman/wfprocessor.py", line 330, in _enqueue
    self._mq_connection.close()
  File "/scratch1/eh22/conda/envs/extasy2/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 688, in close
    self._flush_output(self._closed_result.is_ready)
  File "/scratch1/eh22/conda/envs/extasy2/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 440, in _flush_output
    raise exceptions.ConnectionClosed()
ConnectionClosed

Exception in thread enqueue-thread:
Traceback (most recent call last):
  File "/scratch1/eh22/conda/envs/extasy2/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/scratch1/eh22/conda/envs/extasy2/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/scratch1/eh22/conda/envs/extasy2/lib/python2.7/site-packages/radical/entk/appman/wfprocessor.py", line 348, in _enqueue
    raise Error(text=ex)
Error: Error: 

2018-01-26 00:41:06,988: radical.entk.appmanager: MainProcess                     : MainThread     : ERROR   : Execution interrupted by user (you probably hit Ctrl+C), trying to cancel enqueuer thread gracefully...
2018-01-26 00:41:06,989: radical.entk.wfprocessor: wfprocessor                     : MainThread     : INFO    : Terminating dequeue-thread
2018-01-26 00:41:06,989: radical.entk.appmanager: MainProcess                     : MainThread     : INFO    : Terminating WFprocessor
2018-01-26 00:41:06,990: radical.entk.wfprocessor: wfprocessor                     : dequeue-thread : INFO    : Terminated dequeue thread
2018-01-26 00:41:06,990: radical.entk.wfprocessor: wfprocessor                     : MainThread     : INFO    : WFprocessor process terminated
Process wfprocessor:
Traceback (most recent call last):
  File "/scratch1/eh22/conda/envs/extasy2/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/scratch1/eh22/conda/envs/extasy2/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/scratch1/eh22/conda/envs/extasy2/lib/python2.7/site-packages/radical/entk/appman/wfprocessor.py", line 158, in _wfp
    raise KeyboardInterrupt
KeyboardInterrupt
Process task-manager:
Traceback (most recent call last):
  File "/scratch1/eh22/conda/envs/extasy2/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/scratch1/eh22/conda/envs/extasy2/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/scratch1/eh22/conda/envs/extasy2/lib/python2.7/site-packages/radical/entk/execman/task_manager.py", line 426, in _tmgr
    raise KeyboardInterrupt
KeyboardInterrupt
2018-01-26 00:41:09,262: radical.entk.task_manager: MainProcess                     : heartbeat      : INFO    : Received heartbeat response
2018-01-26 00:41:09,264: radical.entk.task_manager: MainProcess                     : heartbeat      : INFO    : Sent heartbeat request
2018-01-26 00:41:13,990: radical.entk.resource_manager: MainProcess                     : pmgr.0000.idler._state_pull_cb: INFO    : Pilot pilot.0000 state: CANCELED
0 state: CANCELED
^CTraceback (most recent call last):
  File "extasy_grlsd2.py", line 353, in <module>
    appman.run()
  File "/scratch1/eh22/conda/envs/extasy2/lib/python2.7/site-packages/radical/entk/appman/appmanager.py", line 418, in run
    self._wfp.end_processor()
  File "/scratch1/eh22/conda/envs/extasy2/lib/python2.7/site-packages/radical/entk/appman/wfprocessor.py", line 562, in end_processor
    self._logger.debug('Attempting to end WFprocessor... event: %s'%self._wfp_terminate.is_set())
  File "/scratch1/eh22/conda/envs/extasy2/lib/python2.7/multiprocessing/synchronize.py", line 306, in is_set
    self._cond.acquire()
KeyboardInterrupt
^C
```

**Comment by vivek-bala** [comment]
Yes, the termination is somewhat tricky and out of control as it happens within python. We have seen cases where termination can take up to 2 mins.

Also, a single Ctrl+c can be handled where EnTK understands you want to cancel the execution and tries to terminate all the processes (again which can take ~2 mins). But if you Ctrl+c again, then you interrupt the code which is doing the termination. At that point, it is hard to expert proper termination really.

I agree its a usability issue, will keep it in my radar. Thanks!
