### ISSUE TITLE
no self._pilot.cancel()

### ISSUE THREAD

**Issue by euhruska** [radical-collaboration/extasy-grlsd#4]
why doesn't the pilot have self._pilot.cancel()
```
        2017-12-22 19:37:35,391: radical.saga.pty    : MainProcess                     : MainThread     : ERROR   : Could not detect shell prompt (timeout) (/Users/eh/anaconda2/envs/extasy/lib/python2.7/site-packages/saga/utils/pty_shell_factory.py +290 (_initialize_pty)  :  raise se.NoSuccess ("Could not detect shell prompt (timeout)"))
Traceback (most recent call last):
  File "/Users/eh/anaconda2/envs/extasy/lib/python2.7/site-packages/saga/utils/pty_shell_factory.py", line 290, in _initialize_pty
    raise se.NoSuccess ("Could not detect shell prompt (timeout)")
NoSuccess: Could not detect shell prompt (timeout) (/Users/eh/anaconda2/envs/extasy/lib/python2.7/site-packages/saga/utils/pty_shell_factory.py +290 (_initialize_pty)  :  raise se.NoSuccess ("Could not detect shell prompt (timeout)"))
2017-12-22 19:37:35,393: radical.entk.resource_manager: MainProcess                     : MainThread     : ERROR   : Resource request submission failed
2017-12-22 19:37:35,395: radical.entk.appmanager: MainProcess                     : MainThread     : ERROR   : Error in AppManager
Traceback (most recent call last):
  File "/Users/eh/anaconda2/envs/extasy/lib/python2.7/site-packages/radical/entk/appman/appmanager.py", line 240, in run
    self._resource_manager._submit_resource_request()
  File "/Users/eh/anaconda2/envs/extasy/lib/python2.7/site-packages/radical/entk/execman/resource_manager.py", line 323, in _submit_resource_request
    self._pilot = self._pmgr.submit_pilots(pdesc)
  File "/Users/eh/anaconda2/envs/extasy/lib/python2.7/site-packages/radical/pilot/pilot_manager.py", line 503, in submit_pilots
    pilot = ComputePilot(pmgr=self, descr=pd)
  File "/Users/eh/anaconda2/envs/extasy/lib/python2.7/site-packages/radical/pilot/compute_pilot.py", line 103, in __init__
    self._resource_sandbox = self._session._get_resource_sandbox(pilot)
  File "/Users/eh/anaconda2/envs/extasy/lib/python2.7/site-packages/radical/pilot/session.py", line 950, in _get_resource_sandbox
    shell = rsup.PTYShell(js_url, self)
  File "/Users/eh/anaconda2/envs/extasy/lib/python2.7/site-packages/saga/utils/pty_shell.py", line 247, in __init__
    interactive=self.interactive)
  File "/Users/eh/anaconda2/envs/extasy/lib/python2.7/site-packages/saga/utils/pty_shell_factory.py", line 198, in initialize
    self._initialize_pty (info['pty'], info)
  File "/Users/eh/anaconda2/envs/extasy/lib/python2.7/site-packages/saga/utils/pty_shell_factory.py", line 413, in _initialize_pty
    raise ptye.translate_exception (e)
NoSuccess: Could not detect shell prompt (timeout) (/Users/eh/anaconda2/envs/extasy/lib/python2.7/site-packages/saga/utils/pty_shell_factory.py +290 (_initialize_pty)  :  raise se.NoSuccess ("Could not detect shell prompt (timeout)"))

2017-12-22 19:37:35,396: radical.entk.resource_manager: MainProcess                     : MainThread     : ERROR   : Could not cancel resource request, error: 'NoneType' object has no attribute 'cancel'
Error: 'NoneType' object has no attribute 'cancel'
Traceback (most recent call last):
  File "extasy_grlsd.py", line 305, in <module>
    appman.run()
  File "/Users/eh/anaconda2/envs/extasy/lib/python2.7/site-packages/radical/entk/appman/appmanager.py", line 464, in run
    self._resource_manager._cancel_resource_request()
  File "/Users/eh/anaconda2/envs/extasy/lib/python2.7/site-packages/radical/entk/execman/resource_manager.py", line 372, in _cancel_resource_request
    self._pilot.cancel()
AttributeError: 'NoneType' object has no attribute 'cancel'

```

**Comment by euhruska** [comment]
similar to https://github.com/radical-cybertools/saga-python/issues/383

**Comment by euhruska** [comment]
also the part ```("Could not detect shell prompt (timeout)")``` didn't go away when restarting the rabbitmq-server

**Comment by vivek-bala** [comment]
This error is coming from ssh (to BW) taking too long to respond. Unforunately, there isn't much we can do if the machine does not respond quickly. We increase the timeout the ssh command should seek a response for. We can do this by the following:

```
export SAGA_PTY_SSH_TIMEOUT=300
```
