### ISSUE TITLE
two.radical-project.org down?

### ISSUE THREAD

**Issue by euhruska** [radical-collaboration/extasy-grlsd#51]
Is #hostname='two.radical-project.org', port=33134 down?

```Traceback (most recent call last):
  File "/scratch1/eh22/conda/envs/extasy5/lib/python2.7/site-packages/radical/entk/appman/appmanager.py", line 212, in run
    setup = self._setup_mqs()
  File "/scratch1/eh22/conda/envs/extasy5/lib/python2.7/site-packages/radical/entk/appman/appmanager.py", line 495, in _setup_mqs
    port=self._port
  File "/scratch1/eh22/conda/envs/extasy5/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 374, in __init__
    self._process_io_for_connection_setup()
  File "/scratch1/eh22/conda/envs/extasy5/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 414, in _process_io_for_connection_setup
    self._open_error_result.is_ready)
  File "/scratch1/eh22/conda/envs/extasy5/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 468, in _flush_output
    raise exceptions.ConnectionClosed(maybe_exception)
ConnectionClosed: Connection to 138.201.86.166:33134 failed: timeout```

**Comment by andre-merzky** [comment]
Hmm, no, the host seems to be up:

```
 two  merzky  ~   $ hostname -f
two.radical-project.org
 
two  merzky  ~   $ uptime
 07:13:19 up 449 days, 17:17, 48 users,  load average: 1.35, 1.34, 1.35
```

**Comment by vivek-bala** [comment]
The RabbitMQ connected to that port is also up.

> d2d8e3751fa0        rabbitmq:3                     "docker-entrypoint..."   2 weeks ago         Up 2 weeks          0.0.0.0:33136->4369/tcp, 0.0.0.0:33135->5671/tcp, 0.0.0.0:33134->5672/tcp, 0.0.0.0:33133->25672/tcp   extasy-2

Can you test if you can connect to the host alone from the machine you are using?

**Comment by euhruska** [comment]
two.radical-project.org connects, but asks for a password. gsissh bw connects without problems

**Comment by euhruska** [comment]
Seems somehow work now, but the bootstrap.out fails, do I have to reinstall the virtualenv?
```
# -------------------------------------------------------------------
# Touching output tarballs
# -------------------------------------------------------------------
create gtod
build gtod with cc... success
0.0838,bootstrap_1_start,bootstrap_1,MainThread,pilot.0000,PMGR_ACTIVE_PENDING,
VIRTENV : /scratch/sciteam/hruska/radical.pilot.sandbox/ve.ncsa.bw_aprun.0.47.4
VIRTENV : /mnt/c/scratch/sciteam/hruska/radical.pilot.sandbox/ve.ncsa.bw_aprun.0.47.4 (normalized)
PYTHON: /sw/bw/bwpy/mnt/bin/python
PIP   : /sw/bw/bwpy/mnt/bin/pip --cert /scratch/sciteam/hruska/radical.pilot.sandbox/rp.session.leonardo.rice.edu.eh22.017646.0016/pilot.0000/../cacert.pem
2.1855,ve_setup_start,bootstrap_1,MainThread,pilot.0000,PMGR_ACTIVE_PENDING,
virtenv_create   : TRUE
virtenv_update   : FALSE
rp install sources:  radical.utils-0.47.4-merge-pre-gpu-15-g41eea76-devel/ saga-python-0.47-v0.46-72-gc86187fb-fix-issue-663/ radical.pilot-0.47.4-merge-pre-gpu-150-gec325c89-feature-gpu/
rp install target : SANDBOX
rp install lock   : FALSE
rp lock for ve create
obtained lock /mnt/c/scratch/sciteam/hruska/radical.pilot.sandbox/ve.ncsa.bw_aprun.0.47.4.lock
4.0198,ve_create_start,bootstrap_1,MainThread,pilot.0000,PMGR_ACTIVE_PENDING,

# -------------------------------------------------------------------
#
# Download virtualenv tgz
# cmd: curl -k -O 'https://pypi.python.org/packages/source/v/virtualenv/virtualenv-1.9.tar.gz'
#
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
^M  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0^M100   122  100   122    0     0   2837      0 --:--:-- --:--:-- --:--:--  2904
#
# SUCCESS
#
# -------------------------------------------------------------------

# -------------------------------------------------------------------
#
# unpacking virtualenv tgz
# cmd: tar zxmf 'virtualenv-1.9.tar.gz'
#

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
#
# ERROR
# no fallback command available
#
# -------------------------------------------------------------------
Couldn't unpack virtualenv! Using systemv version
ERROR: invalid or unusable virtenv_dist option
Error on virtenv creation -- abort
removed `/mnt/c/scratch/sciteam/hruska/radical.pilot.sandbox/ve.ncsa.bw_aprun.0.47.4.lock'

```

**Comment by andre-merzky** [comment]
You likely are hitting [this](https://github.com/radical-cybertools/radical.pilot/issues/1600)  problem.  The fix was [pushed](https://github.com/radical-cybertools/radical.pilot/commit/192ee5858b9461557061ddc68f0d22ac90f3dcd0) into RP master and released, you likely need to cherry-pick or merge that into whatever branch you use right now.

**Comment by vivek-bala** [comment]
Yes, this seems similar. Pypi changed the format via which they made the tarball accessible and that had to be patched. I saw your email about the missing units. Let me give it another go to see if I can reproduce it.
