### ISSUE TITLE
ana_task tasks behaves different rp and stand-alone

### ISSUE THREAD

**Issue by euhruska** [radical-collaboration/extasy-grlsd#56]
The ana_task tasks fails with mpi4py import error:
```
ModuleCmd_Switch.c(179):ERROR:152: Module 'PrgEnv-cray' is currently not loaded
Traceback (most recent call last):
  File "/var//opt/cray/alps/spool/68773952/lsdmap", line 3, in <module>
    import lsdmap.lsdm as lsdm
  File "/mnt/b/projects/sciteam/bamm/hruska/vpy2/lib/python2.7/site-packages/lsdmap/lsdm.py", line 13, in <module>
    from lsdmap.mpi import p_arpack
  File "/mnt/b/projects/sciteam/bamm/hruska/vpy2/lib/python2.7/site-packages/lsdmap/mpi/p_arpack.py", line 7, in <module>
    from mpi4py import MPI
ImportError: No module named mpi4py
```
But when I run the same command in same environment on bw on it's own there is no issue at all:
```
/opt/xalt/0.7.6/sles11.3/bin/aprun -n 1 -N 1 -d 1 -cc 0 lsdmap "-f" "config.ini" "-c" "tmpha.gro" "-n" "out.nn" "-w" "weight.w"
```

**Comment by andre-merzky** [comment]
When you run manually, is there any `module load` involved, either manually or in your bashrc, which provides MPI4PY?

**Comment by euhruska** [comment]
yes, the same commands in both cases:
mpi4py was installed with pip in vpy2 environment
```'module swap PrgEnv-cray PrgEnv-gnu','module add bwpy','module add bwpy-mpi', 'module add fftw', 'module add cray-netcdf', 'module add cudatoolkit/7.5.18-1.0502.10743.2.1', 'module add cmake', 'module unload darshan, xalt','export CRAYPE_LINK_TYPE=dynamic', 'export CRAY_ADD_RPATH=yes', 'export FC=ftn', 'source /projects/sciteam/bamm/hruska/vpy2/bin/activate'```

**Comment by euhruska** [comment]
the cudatoolkit is not really necessary for this stage, but doesn't hurt

**Comment by andre-merzky** [comment]
Can you attach the complete compute unit description so that I can try to reproduce this?  Thanks!

**Comment by euhruska** [comment]
Is this enough or do you want the logs?
```
ana_stage = Stage()
ana_task = Task()
ana_task.pre_exec = [   
'module swap PrgEnv-cray PrgEnv-gnu','module add bwpy','module add bwpy-mpi', 'module add fftw', 'module add cray-netcdf', 'module add cudatoolkit/7.5.18-1.0502.10743.2.1', 'module add cmake', 'module unload darshan, xalt','export CRAYPE_LINK_TYPE=dynamic', 'export CRAY_ADD_RPATH=yes', 'export FC=ftn', 'source /projects/sciteam/bamm/hruska/vpy2/bin/activate', 'export tasks=lsdmap','export iter=%s' % cur_iter ]
ana_task.executable = ['lsdmap'] #/u/sciteam/hruska/local/bin/lsdmap
ana_task.arguments = ['-f', os.path.basename(Kconfig.lsdm_config_file),
                      '-c', 'tmpha.gro',
                      '-n', 'out.nn',
                      '-w', 'weight.w'
                      ]

ana_task.cores = 1
ana_task.link_input_data = ['$SHARED/{0} > {0}'.format(os.path.basename(Kconfig.lsdm_config_file)),
                            '%s/iter_%s/tmpha.gro > tmpha.gro' % (combined_path,cur_iter)]
ana_task.copy_output_data = ['tmpha.ev > $SHARED/iter_%s/tmpha.ev' % cur_iter,
                             'tmpha.eg > $SHARED/iter_%s/tmpha.eg' % cur_iter,
                             'lsdmap.log > output/iter_%s/lsdmap.log'%cur_iter,
                             'tmpha.ev > %s/iter_%s/tmpha.ev' % (combined_path,cur_iter),
                             'tmpha.eps > %s/iter_%s/tmpha.eps' % (combined_path,cur_iter),
                             'tmpha.eg > %s/iter_%s/tmpha.eg' % (combined_path,cur_iter),
                             'out.nn > %s/iter_%s/out.nn' % (combined_path,cur_iter),
                             'lsdmap.log > %s/iter_%s/lsdmap.log' % (combined_path,cur_iter)
                             ]
if cur_iter > 0:
    ana_task.link_input_data += ['%s/iter_%s/weight_out.w > weight.w' % (combined_path,cur_iter-1)]

if(cur_iter % Kconfig.nsave == 0):
    ana_task.download_output_data = ['lsdmap.log > output/iter_%s/lsdmap.log' % cur_iter]

ana_task_ref = '$Pipeline_%s_Stage_%s_Task_%s'%(wf.uid, ana_stage.uid, ana_task.uid)


ana_stage.add_tasks(ana_task)
wf.add_stages(ana_stage)
```

**Comment by andre-merzky** [comment]
This should suffice - thanks!

**Comment by euhruska** [comment]
And idea what I could try?

**Comment by vivek-bala** [comment]
I'll wait for Andre to comment. Meanwhile, can you confirm that you can run the following:
```
source /mnt/b/projects/sciteam/bamm/hruska/vpy2/bin/activate
$ python -c "from mpi4py import MPI"
```

Also can you paste the .sh file that exists inside the unit folder please. Thanks.

**Comment by euhruska** [comment]
```
source /mnt/b/projects/sciteam/bamm/hruska/vpy2/bin/activate
$ python -c "from mpi4py import MPI"
```
fails with:
```
[Mon Aug  6 12:49:46 2018] [unknown] Fatal error in PMPI_Init_thread: Other MPI error, error stack:
MPIR_Init_thread(525):
MPID_Init(225).......: channel initialization failed
MPID_Init(598).......:  PMI2 init failed: 1
Aborted
```

content of unit.000006.sh:
```
#!/bin/sh


# Environment variables
export RP_SESSION_ID="rp.session.leonardo.rice.edu.eh22.017745.0005"
export RP_PILOT_ID="pilot.0000"
export RP_AGENT_ID="agent_0"
export RP_SPAWNER_ID="agent_0.executing.0.child"
export RP_UNIT_ID="unit.000006"
export RP_GTOD="/mnt/c/scratch/sciteam/hruska/radical.pilot.sandbox/rp.session.leonardo.rice.edu.eh22.017745.0005/pilot.0000/gtod"
export RP_TMP="None"
export RP_PROF="/mnt/c/scratch/sciteam/hruska/radical.pilot.sandbox/rp.session.leonardo.rice.edu.eh22.017745.0005/pilot.0000/unit.000006/unit.000006.prof"

prof(){
    if test -z "$RP_PROF"
    then
        return
    fi
    event=$1
    now=$($RP_GTOD)
    echo "$now,$event,unit_script,MainThread,$RP_UNIT_ID,AGENT_EXECUTING," >> $RP_PROF
}
export OMP_NUM_THREADS="1"


touch $RP_PROF
prof cu_start

# Change to unit sandbox
cd /mnt/c/scratch/sciteam/hruska/radical.pilot.sandbox/rp.session.leonardo.rice.edu.eh22.017745.0005/pilot.0000/unit.000006
prof cu_cd_done

# Pre-exec commands
prof cu_pre_start
module swap PrgEnv-cray PrgEnv-gnu ||  (echo "pre_exec failed"; false) || exit
module add bwpy ||  (echo "pre_exec failed"; false) || exit
module add bwpy-mpi ||  (echo "pre_exec failed"; false) || exit
module add fftw ||  (echo "pre_exec failed"; false) || exit
module add cray-netcdf ||  (echo "pre_exec failed"; false) || exit
module add cudatoolkit/7.5.18-1.0502.10743.2.1 ||  (echo "pre_exec failed"; false) || exit
module add cmake ||  (echo "pre_exec failed"; false) || exit
module unload darshan, xalt ||  (echo "pre_exec failed"; false) || exit
export CRAYPE_LINK_TYPE=dynamic ||  (echo "pre_exec failed"; false) || exit
export CRAY_ADD_RPATH=yes ||  (echo "pre_exec failed"; false) || exit
export FC=ftn ||  (echo "pre_exec failed"; false) || exit
source /projects/sciteam/bamm/hruska/vpy2/bin/activate ||  (echo "pre_exec failed"; false) || exit
export tasks=lsdmap ||  (echo "pre_exec failed"; false) || exit
export iter=0 ||  (echo "pre_exec failed"; false) || exit
export OMP_NUM_THREADS=1 ||  (echo "pre_exec failed"; false) || exit
prof cu_pre_stop

# The command to run
prof cu_exec_start
/opt/xalt/0.7.6/sles11.3/bin/aprun -n 1 -N 1 -L 11660 -d 1 -cc 0 lsdmap "-f" "config.ini" "-c" "tmpha.gro" "-n" "out.nn" "-w" "weight.w"
RETVAL=$?
prof cu_exec_stop

# Exit the script with the return code from the command
prof cu_stop
exit $RETVAL
```

**Comment by euhruska** [comment]
adding 
```
export LD_LIBRARY_PATH=/projects/sciteam/bamm/hruska/vpy2/lib:$LD_LIBRARY_PATH
``` 
doesn't help

**Comment by vivek-bala** [comment]
Okay. The shell script looks correct. Can you try the earlier cmd inside the aprun environment as follows:
```
qsub -I -l nodes=1:ppn=16:xe -l walltime=00:20:00      # Get an interactive node
<load all modules>
source /mnt/b/projects/sciteam/bamm/hruska/vpy2/bin/activate
/opt/xalt/0.7.6/sles11.3/bin/aprun -n 1 python -c "from mpi4py import MPI"
aprun -n 1 python -c "from mpi4py import MPI"
```

**Comment by euhruska** [comment]
No errors with either of them
/opt/xalt/0.7.6/sles11.3/bin/aprun or aprun

**Comment by vivek-bala** [comment]
Okay. Thanks for trying. I think this might be an issue with the CU environment. Andre can probably suggest how to resolve this.

**Comment by andre-merzky** [comment]
I also don't see what's up with that, really.  I guess we can narrow this down by submitting (a reduced version of) the CU startup script via qsub.  @euhruska , can you try to submit this script:

```

export OMP_NUM_THREADS="1"

module swap PrgEnv-cray PrgEnv-gnu ||  (echo "pre_exec failed"; false) || exit
module add bwpy ||  (echo "pre_exec failed"; false) || exit
module add bwpy-mpi ||  (echo "pre_exec failed"; false) || exit
module add fftw ||  (echo "pre_exec failed"; false) || exit
module add cray-netcdf ||  (echo "pre_exec failed"; false) || exit
module add cudatoolkit/7.5.18-1.0502.10743.2.1 ||  (echo "pre_exec failed"; false) || exit
module add cmake ||  (echo "pre_exec failed"; false) || exit
module unload darshan, xalt ||  (echo "pre_exec failed"; false) || exit
export CRAYPE_LINK_TYPE=dynamic ||  (echo "pre_exec failed"; false) || exit
export CRAY_ADD_RPATH=yes ||  (echo "pre_exec failed"; false) || exit
export FC=ftn ||  (echo "pre_exec failed"; false) || exit
source /projects/sciteam/bamm/hruska/vpy2/bin/activate ||  (echo "pre_exec failed"; false) || exit
export tasks=lsdmap ||  (echo "pre_exec failed"; false) || exit
export iter=0 ||  (echo "pre_exec failed"; false) || exit
export OMP_NUM_THREADS=1 ||  (echo "pre_exec failed"; false) || exit

/opt/xalt/0.7.6/sles11.3/bin/aprun -n 1 -N 1 -L 11660 -d 1 -cc 0 lsdmap "-f" "config.ini" "-c" "tmpha.gro" "-n" "out.nn" "-w" "weight.w"
```

Thanks!

**Comment by euhruska** [comment]
had to remove ```-L 11660 ``` because ```apsched: user-specified NIDs in command 0 do not match the confirmed NIDs```,  changed to module unload darshan xalt and module add bwpy/0.3.0. But then it worked, no error

**Comment by euhruska** [comment]
adding these changes to the script fixed this issue
