### ISSUE TITLE
sudden stop of launching units

### ISSUE THREAD

**Issue by euhruska** [radical-collaboration/extasy-grlsd#64]
entk had to launch 8 units, but launched only 4 and then gave this error. It looks like a connection error. Is there a way to prevent this?
```
2018-08-10 15:28:40,066: radical.entk.task_manager.0000: task-manager                    : umgr.0000.subscriber._state_sub_cb: ERRO$
   : Error in RP callback thread: 'NoneType' object has no attribute 'clear'
Traceback (most recent call last):
  File "/scratch1/eh22/conda/envs/extasy9/lib/python2.7/site-packages/radical/entk/execman/task_manager.py", line 282, in unit_stat$
_cb
    self._mq_connection.close()
  File "/scratch1/eh22/conda/envs/extasy9/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 730, in close
    self._flush_output(self._closed_result.is_ready)
  File "/scratch1/eh22/conda/envs/extasy9/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 458, in _flush_ou$
put
    self._impl.ioloop.poll()
  File "/scratch1/eh22/conda/envs/extasy9/lib/python2.7/site-packages/pika/adapters/select_connection.py", line 495, in poll
    self._poller.poll()
  File "/scratch1/eh22/conda/envs/extasy9/lib/python2.7/site-packages/pika/adapters/select_connection.py", line 1114, in poll
    self._dispatch_fd_events(fd_event_map)
  File "/scratch1/eh22/conda/envs/extasy9/lib/python2.7/site-packages/pika/adapters/select_connection.py", line 815, in _dispatch_f$
_events
    self._processing_fd_event_map.clear()
AttributeError: 'NoneType' object has no attribute 'clear'

```

**Comment by vivek-bala** [comment]
Looks the same as #65
