### ISSUE TITLE
heartbeat fails

### ISSUE THREAD

**Issue by euhruska** [radical-collaboration/extasy-grlsd#65]
an otherwise good run just failed because the below heartbeat issue, is there a way to prevent this?

```
2018-08-11 15:52:10,636: radical.entk.task_manager.0000: task-manager                    : MainThread     : INFO    : Sent heartbeat r$
sponse
Traceback (most recent call last):
  File "/scratch1/eh22/conda/envs/extasy9/lib/python2.7/site-packages/radical/entk/execman/task_manager.py", line 436, in _tmgr
    self._mq_connection.close()
  File "/scratch1/eh22/conda/envs/extasy9/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 730, in close
    self._flush_output(self._closed_result.is_ready)
  File "/scratch1/eh22/conda/envs/extasy9/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 458, in _flush_outpu$
    self._impl.ioloop.poll()
  File "/scratch1/eh22/conda/envs/extasy9/lib/python2.7/site-packages/pika/adapters/select_connection.py", line 495, in poll
    self._poller.poll()
  File "/scratch1/eh22/conda/envs/extasy9/lib/python2.7/site-packages/pika/adapters/select_connection.py", line 1114, in poll
    self._dispatch_fd_events(fd_event_map)
  File "/scratch1/eh22/conda/envs/extasy9/lib/python2.7/site-packages/pika/adapters/select_connection.py", line 815, in _dispatch_fd_e$
ents
    self._processing_fd_event_map.clear()
AttributeError: 'NoneType' object has no attribute 'clear'

Process task-manager:
Traceback (most recent call last):
  File "/scratch1/eh22/conda/envs/extasy9/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/scratch1/eh22/conda/envs/extasy9/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/scratch1/eh22/conda/envs/extasy9/lib/python2.7/site-packages/radical/entk/execman/task_manager.py", line 449, in _tmgr
    raise Error(text=ex)
Error: Error: 'NoneType' object has no attribute 'clear'
2018-08-11 15:52:31,945: radical.entk.task_manager.0000: MainProcess                     : MainThread     : INFO    : Task manager process closed
2018-08-11 15:52:31,945: radical.entk.appmanager.0000: MainProcess                     : MainThread     : INFO    : Restarting task man
ager process from AppManager
2018-08-11 15:52:31,945: radical.entk.task_manager.0000: MainProcess                     : MainThread     : WARNING : tmgr process alre
ady running, but attempted to restart!
```

**Comment by vivek-bala** [comment]
This is a new one! Can you attach the entire EnTK log output please? You can capture the standard output stream to a file by doing something like [this](https://stackoverflow.com/questions/418896/how-to-redirect-output-to-a-file-and-stdout#418899)

**Comment by euhruska** [comment]
will post if it happens again
restarting the whole python environment and rabbitmq stopped it happening

**Comment by euhruska** [comment]
Happened again:
[entk.log](https://github.com/radical-collaboration/extasy-grlsd/files/2287535/entk.log)
[re.session.leonardo.rice.edu.eh22.017757.0010.zip](https://github.com/radical-collaboration/extasy-grlsd/files/2287542/re.session.leonardo.rice.edu.eh22.017757.0010.zip)
[rp.session.leonardo.rice.edu.eh22.017757.0011.zip](https://github.com/radical-collaboration/extasy-grlsd/files/2287543/rp.session.leonardo.rice.edu.eh22.017757.0011.zip)

**Comment by euhruska** [comment]
solved by https://github.com/radical-collaboration/extasy-grlsd/issues/52
