### ISSUE TITLE
module load bw

### ISSUE THREAD

**Issue by euhruska** [radical-collaboration/extasy-grlsd#81]
```
bwpy/2.0.0-pre0(16):ERROR:150: Module 'bwpy/2.0.0-pre0' conflicts with the currently loaded module(s) 'bwpy/1.2.4'
bwpy/2.0.0-pre0(16):ERROR:102: Tcl command execution failed: conflict bwpy

Traceback (most recent call last):
  File "/mnt/bwpy/single/usr/lib/python3.5/site-packages/simtk/openmm/openmm.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
  File "/mnt/b/projects/sciteam/bamm/hruska/vpy8/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 985, in _gcd_import
  File "<frozen importlib._bootstrap>", line 968, in _find_and_load
  File "<frozen importlib._bootstrap>", line 957, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 666, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 577, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 938, in create_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
ImportError: /opt/gcc/4.9.3/snos/lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /mnt/bwpy/single/usr/lib/python3.5/site-packages/simtk/openmm/_openmm.cpython-35m-x86_64-linux-gnu.so)
```

**Comment by euhruska** [comment]
the issue is, I didn't load bwpy/1.2.4
