### ISSUE TITLE
environment fails 

### ISSUE THREAD

**Issue by euhruska** [radical-collaboration/extasy-grlsd#82]
this environment works no problem standalone on bw, but fails with extasy:
```
module unload bwpy 
module load bwpy/2.0.0-pre0 
module load bwpy-mpi
module add cudatoolkit 
export MODULEPATH="/sw/bw/bwpy/modulefiles/:${MODULEPATH}" 
export CPATH="${BWPY_INCLUDE_PATH}"
export LDFLAGS="${LDFLAGS} -Wl,--rpath=${BWPY_LIBRARY_PATH}" 
module load craype-ml-plugin-py3/1.1.0 
export MPICH_GNI_MALLOC_FALLBACK=enable 
export MPICH_GNI_MAX_VSHORT_MSG_SIZE=64 
export MPICH_MAX_THREAD_SAFETY=multiple 
export MPICH_RMA_OVER_DMAPP=1 
export OPENMM_PLUGIN_DIR=/mnt/bwpy/single/usr/lib/plugins 
source /projects/sciteam/bamm/hruska/vpy8/bin/activate 
bwpy-environ 
/opt/xalt/0.7.6/sles11.3/bin/aprun -n 1 -N 1 -d 1 -cc 0 bwpy-environ "python" "run_openmm.py" "--trajstride" "10" "--idxstart" "75" "--idxend" "100" "--path" "/u/sciteam/hruska/scratch/extasy_tica3-ntl9-small" "--iter" "0" "--md_steps" "10000" "--save_traj" "True"
```
error with extasy
```
Traceback (most recent call last):
  File "run_openmm.py", line 9, in <module>
    import mdtraj as md
  File "/mnt/b/projects/sciteam/bamm/hruska/vpy8/lib/python3.5/site-packages/mdtraj/__init__.py", line 29, in <module>
    from .formats.registry import FormatRegistry
  File "/mnt/b/projects/sciteam/bamm/hruska/vpy8/lib/python3.5/site-packages/mdtraj/formats/__init__.py", line 15, in <module>
    from .dtr import DTRTrajectoryFile
ImportError: /opt/gcc/4.9.3/snos/lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /mnt/b/projects/sciteam/bamm/hruska/vpy8/lib/python3.5/site-packages/mdtraj/formats/dtr.cpython-35m-x86_64-linux-gnu.so)
```

I believe I use the same commands, but still there is this difference

**Comment by euhruska** [comment]
this error was solved by loading the right gcc
