### ISSUE TITLE
openmm error

### ISSUE THREAD

**Issue by euhruska** [radical-collaboration/extasy-grlsd#89]
usually doesn't happen, why?
```
Traceback (most recent call last):
  File "run_openmm.py", line 139, in <module>
    simulation.context.setPositions(pdb.positions)
  File "/mnt/bwpy/single/usr/lib/python3.5/site-packages/simtk/openmm/openmm.py", line 13629, in setPositions
    return _openmm.Context_setPositions(self, positions)
Exception: Called setPositions() on a Context with the wrong number of positions
```

**Comment by euhruska** [comment]
doesn't happen anymore
