### ISSUE TITLE
unsupported operand type(s) for +: 'float' and 'str'

### ISSUE THREAD

**Issue by euhruska** [radical-collaboration/extasy-grlsd#96]
@vivek-bala getting errors, not sure what changed:

```
2018-10-01 06:48:06,760: radical.entk.task_manager.0000: MainProcess                     : heartbeat      : ERROR   : Heartbeat failed with error: unsupported operand type(s) for +: 'float' and 'str'
Traceback (most recent call last):
  File "/scratch1/eh22/conda/envs/extasy11/lib/python2.7/site-packages/radical/entk/execman/base/task_manager.py", line 145, in _heartbeat
    mq_connection.sleep(self._hb_interval)
  File "/scratch1/eh22/conda/envs/extasy11/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 771, in sleep
    deadline = time.time() + duration
TypeError: unsupported operand type(s) for +: 'float' and 'str'
Exception in thread heartbeat:
Traceback (most recent call last):
  File "/scratch1/eh22/conda/envs/extasy11/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/scratch1/eh22/conda/envs/extasy11/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/scratch1/eh22/conda/envs/extasy11/lib/python2.7/site-packages/radical/entk/execman/base/task_manager.py", line 145, in _heartbeat
    mq_connection.sleep(self._hb_interval)
  File "/scratch1/eh22/conda/envs/extasy11/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 771, in sleep
    deadline = time.time() + duration
TypeError: unsupported operand type(s) for +: 'float' and 'str'
```
and 
```
2018-10-01 06:47:15,858: radical.entk.task_manager.0000: MainProcess                     : heartbeat      : ERROR   : Heartbeat failed with error: unsupported operand type(s) for +:
 'float' and 'str'
Traceback (most recent call last):
  File "/scratch1/eh22/conda/envs/extasy11/lib/python2.7/site-packages/radical/entk/execman/base/task_manager.py", line 145, in _heartbeat
    mq_connection.sleep(self._hb_interval)
  File "/scratch1/eh22/conda/envs/extasy11/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 771, in sleep
    deadline = time.time() + duration
TypeError: unsupported operand type(s) for +: 'float' and 'str'
```

**Comment by vivek-bala** [comment]
Hey Eugen, please try the [fix/issue_extasy_96](https://github.com/radical-cybertools/radical.entk/tree/fix/issue_extasy_96) branch of EnTK. This issue should be resolved there.

**Comment by euhruska** [comment]
works
